// Generated by tools/build-content.js from content/**/*.md. Do not edit by hand.
window.LAB_CONTENT = {
  "defaultLanguage": "ru",
  "languageStorageKey": "wireless-lab-language",
  "themes": [
    {
      "key": "Academic Pages",
      "href": "themes-preview/academicpages/",
      "title": {
        "ru": "Academic Pages",
        "en": "Academic Pages"
      },
      "description": {
        "ru": "Академический стиль Jekyll",
        "en": "Jekyll academic style"
      }
    },
    {
      "key": "Hugo Academic / Hugo Blox",
      "href": "themes-preview/hugo-academic/",
      "title": {
        "ru": "Hugo Academic / Hugo Blox",
        "en": "Hugo Academic / Hugo Blox"
      },
      "description": {
        "ru": "Современный стиль исследовательской группы",
        "en": "Modern research group style"
      }
    },
    {
      "key": "Minimal Mistakes",
      "href": "themes-preview/minimal-mistakes/",
      "title": {
        "ru": "Minimal Mistakes",
        "en": "Minimal Mistakes"
      },
      "description": {
        "ru": "Гибкий академический документационный стиль",
        "en": "Academic documentation style"
      }
    },
    {
      "key": "Bootstrap Academic",
      "href": "themes-preview/bootstrap-academic/",
      "title": {
        "ru": "Bootstrap Academic",
        "en": "Bootstrap Academic"
      },
      "description": {
        "ru": "Современный стиль Bootstrap/Vite",
        "en": "Modern Bootstrap/Vite style"
      }
    }
  ],
  "languages": {
    "ru": {
      "labName": "лаборатория беспроводной связи",
      "tagline": "Исследовательская группа в области систем беспроводной связи",
      "rootEyebrow": "Среда сравнения тем",
      "rootLead": "Выберите один вариант академического сайта.",
      "themeSelector": "Выбор темы",
      "home": "Главная",
      "sections": [
        {
          "key": "people",
          "title": "Участники",
          "href": "people.html"
        },
        {
          "key": "students",
          "title": "Студентам",
          "href": "students.html"
        },
        {
          "key": "projects",
          "title": "Проекты",
          "href": "projects.html"
        },
        {
          "key": "publications",
          "title": "Публикации",
          "href": "publications.html"
        },
        {
          "key": "media",
          "title": "Медиа",
          "href": "media.html"
        },
        {
          "key": "news",
          "title": "Новости",
          "href": "news.html"
        }
      ],
      "sectionLabels": {
        "researchKicker": "Научные направления",
        "researchTitle": "Исследования",
        "peopleKicker": "Команда лаборатории",
        "peopleTitle": "Участники",
        "studentsKicker": "Для студентов",
        "studentsTitle": "Не знаешь -- научим",
        "projectsKicker": "Текущая работа",
        "projectsTitle": "Проекты",
        "publicationsKicker": "Результаты",
        "publicationsTitle": "Публикации",
        "mediaKicker": "Медиа",
        "mediaTitle": "Медиа",
        "newsKicker": "Новости лаборатории",
        "newsTitle": "Новости"
      },
      "researchInterests": [
        {
          "title": "5G/6G",
          "text": "Исследование технологий мобильной связи пятого и шестого поколений, включая архитектуры сетей, радиоинтерфейсы и сценарии сверхнадёжной передачи данных."
        },
        {
          "title": "Polar codes",
          "text": "Изучение полярных кодов как класса помехоустойчивого кодирования для современных и перспективных систем связи."
        },
        {
          "title": "Next-generation multiple access",
          "text": "Методы множественного доступа нового поколения для эффективного совместного использования радиоресурсов большим числом устройств."
        },
        {
          "title": "RIS",
          "text": "Reconfigurable Intelligent Surfaces для управления распространением радиосигнала и повышения качества беспроводных каналов."
        }
      ],
      "peopleGroups": [
        {
          "title": "Старшие научные сотрудники",
          "people": [
            "Покаместов Дмитрий Алексеевич",
            "Крюков Яков Владимирович",
            "Литвинов Рудольф Викторович"
          ]
        },
        {
          "title": "Инженеры",
          "people": [
            "Степной Виктор Серафимович"
          ]
        },
        {
          "title": "Аспиранты",
          "people": [
            "Шинкевич Артём Сергеевич",
            "Шалин Георгий Николаевич",
            "Еремеев Сергей Александрович",
            "Ильинский Дмитрий Евгеньевич"
          ]
        },
        {
          "title": "Студенты",
          "people": [
            "Погорелов Евгений Батькович"
          ]
        }
      ],
      "placeholders": {
        "email": "Email",
        "orcid": "ORCID",
        "scholar": "Google Scholar",
        "profile": "Внешний профиль",
        "value": "заглушка",
        "todo": "TODO",
        "media": "Заглушка"
      },
      "studentOffer": {
        "lead": "",
        "steps": [
          {
            "title": "Войти в тему",
            "text": "Объясним основы 5G/6G, кодирования, множественного доступа и RIS понятным языком."
          },
          {
            "title": "Получить задачу",
            "text": "Подберём небольшой исследовательский или инженерный фрагмент под текущий уровень подготовки."
          },
          {
            "title": "Сделать результат",
            "text": "Поможем оформить эксперимент, прототип, доклад, курсовую или выпускную работу."
          }
        ],
        "tracks": [
          "Моделирование систем связи",
          "Кодирование и обработка сигналов",
          "Сетевые эксперименты",
          "Научное письмо и доклады"
        ]
      },
      "projects": [
        {
          "title": "Заглушка проекта 1",
          "text": "Место для описания исследовательского проекта лаборатории."
        },
        {
          "title": "Заглушка проекта 2",
          "text": "Место для описания совместной работы по беспроводным системам."
        },
        {
          "title": "Заглушка проекта 3",
          "text": "Место для описания экспериментального исследования сетей связи."
        }
      ],
      "publicationSections": [
        "Международные журналы",
        "Российские журналы",
        "Патенты"
      ],
      "mediaSections": [
        "Фотографии лаборатории",
        "Фотографии исследовательской деятельности",
        "Фотографии конференций"
      ],
      "newsItems": [
        {
          "date": "Дата уточняется",
          "title": "Новость лаборатории",
          "text": "Место для объявления лаборатории."
        },
        {
          "date": "Дата уточняется",
          "title": "Научное событие",
          "text": "Место для новости об исследовательской активности."
        },
        {
          "date": "Дата уточняется",
          "title": "Конференция или семинар",
          "text": "Место для новости о мероприятии."
        }
      ]
    },
    "en": {
      "labName": "Wireless Communication Laboratory",
      "tagline": "Research group in wireless communication systems",
      "rootEyebrow": "Theme comparison environment",
      "rootLead": "Select one academic website style preview.",
      "themeSelector": "Theme selector",
      "home": "Home",
      "sections": [
        {
          "key": "people",
          "title": "People",
          "href": "people.html"
        },
        {
          "key": "students",
          "title": "For Students",
          "href": "students.html"
        },
        {
          "key": "projects",
          "title": "Projects",
          "href": "projects.html"
        },
        {
          "key": "publications",
          "title": "Publications",
          "href": "publications.html"
        },
        {
          "key": "media",
          "title": "Media",
          "href": "media.html"
        },
        {
          "key": "news",
          "title": "News",
          "href": "news.html"
        }
      ],
      "sectionLabels": {
        "researchKicker": "Research Interests",
        "researchTitle": "Research",
        "peopleKicker": "Laboratory Team",
        "peopleTitle": "People",
        "studentsKicker": "For Students",
        "studentsTitle": "If you do not know yet, we will teach you",
        "projectsKicker": "Current Work",
        "projectsTitle": "Projects",
        "publicationsKicker": "Outputs",
        "publicationsTitle": "Publications",
        "mediaKicker": "Media",
        "mediaTitle": "Media",
        "newsKicker": "Laboratory News",
        "newsTitle": "News"
      },
      "researchInterests": [
        {
          "title": "5G/6G",
          "text": "Research on fifth- and sixth-generation mobile communication technologies, including network architectures, radio interfaces, and ultra-reliable data transmission scenarios."
        },
        {
          "title": "Polar codes",
          "text": "Study of polar codes as an error-correcting coding class for current and future communication systems."
        },
        {
          "title": "Next-generation multiple access",
          "text": "Next-generation multiple access methods for efficient radio resource sharing across large numbers of devices."
        },
        {
          "title": "RIS",
          "text": "Reconfigurable Intelligent Surfaces for controlling radio propagation and improving wireless channel quality."
        }
      ],
      "peopleGroups": [
        {
          "title": "Senior Researchers",
          "people": [
            "Покаместов Дмитрий Алексеевич",
            "Крюков Яков Владимирович",
            "Литвинов Рудольф Викторович"
          ]
        },
        {
          "title": "Engineers",
          "people": [
            "Степной Виктор Серафимович"
          ]
        },
        {
          "title": "PhD Students",
          "people": [
            "Шинкевич Артём Сергеевич",
            "Шалин Георгий Николаевич",
            "Еремеев Сергей Александрович",
            "Ильинский Дмитрий Евгеньевич"
          ]
        },
        {
          "title": "Students",
          "people": [
            "Погорелов Евгений Батькович"
          ]
        }
      ],
      "placeholders": {
        "email": "Email",
        "orcid": "ORCID",
        "scholar": "Google Scholar",
        "profile": "External profile",
        "value": "placeholder",
        "todo": "TODO",
        "media": "Placeholder"
      },
      "studentOffer": {
        "lead": "",
        "steps": [
          {
            "title": "Enter the field",
            "text": "We explain the fundamentals of 5G/6G, coding, multiple access, and RIS in clear terms."
          },
          {
            "title": "Get a task",
            "text": "We help select a small research or engineering task that matches the student's current level."
          },
          {
            "title": "Produce a result",
            "text": "We support experiments, prototypes, talks, coursework, and graduation projects."
          }
        ],
        "tracks": [
          "Communication system modeling",
          "Coding and signal processing",
          "Network experiments",
          "Scientific writing and talks"
        ]
      },
      "projects": [
        {
          "title": "Project placeholder 1",
          "text": "Placeholder for a laboratory research project."
        },
        {
          "title": "Project placeholder 2",
          "text": "Placeholder for a collaborative wireless systems activity."
        },
        {
          "title": "Project placeholder 3",
          "text": "Placeholder for an experimental communication networks study."
        }
      ],
      "publicationSections": [
        "International Journals",
        "Russian Journals",
        "Patents"
      ],
      "mediaSections": [
        "Laboratory photos",
        "Research activity photos",
        "Conference photos"
      ],
      "newsItems": [
        {
          "date": "Date TBD",
          "title": "Laboratory news",
          "text": "Placeholder for a laboratory announcement."
        },
        {
          "date": "Date TBD",
          "title": "Research activity",
          "text": "Placeholder for a research activity update."
        },
        {
          "date": "Date TBD",
          "title": "Conference or seminar",
          "text": "Placeholder for an event update."
        }
      ]
    }
  }
};
