const fs = require("fs");
const path = require("path");

const root = path.resolve(__dirname, "..");
const contentRoot = path.join(root, "content");
const languages = ["ru", "en"];
const sectionFolders = [
  "home",
  "people",
  "students",
  "projects",
  "publications",
  "media",
  "news"
];

function readJsonBlock(filePath) {
  const markdown = fs.readFileSync(filePath, "utf8");
  const match = markdown.match(/```json\s*([\s\S]*?)\s*```/);

  if (!match) {
    throw new Error(`Missing JSON block in ${filePath}`);
  }

  try {
    return JSON.parse(match[1]);
  } catch (error) {
    throw new Error(`Invalid JSON in ${filePath}: ${error.message}`);
  }
}

const site = readJsonBlock(path.join(root, "content", "site.md"));

function mergeContent(target, source) {
  Object.entries(source).forEach(([key, value]) => {
    if (key === "sectionLabels" || key === "placeholders") {
      target[key] = { ...(target[key] || {}), ...value };
      return;
    }

    target[key] = value;
  });

  return target;
}

function readSection(lang, section) {
  return readJsonBlock(path.join(contentRoot, section, `${lang}.md`));
}

function readNewsItems(lang) {
  const itemsRoot = path.join(contentRoot, "news", "items");

  if (!fs.existsSync(itemsRoot)) {
    return [];
  }

  return fs.readdirSync(itemsRoot, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .sort()
    .map((itemDir) => readJsonBlock(path.join(itemsRoot, itemDir, `${lang}.md`)));
}

function buildLanguage(lang) {
  const data = readSection(lang, "navigation");

  sectionFolders.forEach((section) => {
    mergeContent(data, readSection(lang, section));
  });

  data.newsItems = readNewsItems(lang);

  return data;
}

const content = {
  defaultLanguage: site.defaultLanguage,
  languageStorageKey: site.languageStorageKey,
  themes: site.themes,
  languages: Object.fromEntries(languages.map((lang) => [lang, buildLanguage(lang)]))
};

const output = `// Generated by tools/build-content.js from content/**/*.md. Do not edit by hand.
window.LAB_CONTENT = ${JSON.stringify(content, null, 2)};
`;

fs.writeFileSync(path.join(root, "js", "lab-content.js"), output, "utf8");
console.log("Generated js/lab-content.js from content/**/*.md");
