const fs = require("fs");
const path = require("path");

const root = path.resolve(__dirname, "..");

function readJsonBlock(filePath) {
  const markdown = fs.readFileSync(filePath, "utf8");
  const match = markdown.match(/```json\s*([\s\S]*?)\s*```/);

  if (!match) {
    throw new Error(`Missing JSON block in ${filePath}`);
  }

  try {
    return JSON.parse(match[1]);
  } catch (error) {
    throw new Error(`Invalid JSON in ${filePath}: ${error.message}`);
  }
}

const site = readJsonBlock(path.join(root, "content", "site.md"));
const ru = readJsonBlock(path.join(root, "content", "ru.md"));
const en = readJsonBlock(path.join(root, "content", "en.md"));

const content = {
  defaultLanguage: site.defaultLanguage,
  languageStorageKey: site.languageStorageKey,
  themes: site.themes,
  languages: { ru, en }
};

const output = `// Generated by tools/build-content.js from content/*.md. Do not edit by hand.
window.LAB_CONTENT = ${JSON.stringify(content, null, 2)};
`;

fs.writeFileSync(path.join(root, "js", "lab-content.js"), output, "utf8");
console.log("Generated js/lab-content.js from content/*.md");
